- hosts: all
  gather_facts: no
  vars: 
    my_versions:
      - name: version_1
        version: 1
        released: yes
        license: abc
      - name: version_2
        version: 2
        released: no
        license: abcd

  tasks:      
    - debug: msg={{ my_versions[number|int] }}
    
    - name: check released version
      debug: msg={{ my_versions[number|int]["version"] }}
      when: "{{ my_versions[number|int]['released'] }}" == true
