---
- hosts: server_55

  tasks:
  - name: check apache
    shell: `which yum` info httpd
    register: httpd_output
    
  - debug: msg="about httpd - {{ httpd_output.stdout_lines }}"
    
  - name: ensure apache is running (and enable it at boot)
    service: name=httpd state=started enabled=yes
    
- hosts: server_56

  tasks:
  - name: check postgresql
    shell: `which yum` info postgresql
    
  - name: ensure that postgresql is started
    service: name=postgresql state=started
