---
- hosts: server_55

  tasks:
    - name: 1. install Apache
      apt: name=apache2 state=present

    - name: 2. install PHP module for Apache
      apt: name=libapache2-mod-php5 state=present

    - name: 3. start Apache
      service: name=apache2 state=running enabled=yes

- hosts: server_56

  tasks:
  - name: ensure postgresql is at the latest version
    yum: name=postgresql state=latest
    
  - name: ensure that postgresql is started
    service: name=postgresql state=started
