- hosts: all
  gather_facts: yes
  vars: 
    my_versions:
      - name: version_1
        version: 1
        released: yes
        license: abc
      - name: version_2
        version: 2
        released: no
        license: abcd

  tasks:      
    - set_fact: current={{ my_versions[number|int] }}
    
    - set_stats: 
        data:
          foo: bar
    
    - command: pwd
      register: pwd_result
      
    - name: check the version specified
      debug: msg={{ current }}
    
    - name: check released version
      debug: msg={{ item.version }}
      with_items: "{{ my_versions }}"
      when: "{{ item.released }}"
      
    # Aggregating packages_installed stat per host
    - set_stats:
        data:
            packages_installed: 31

    # setting stats (not aggregating)
    - set_stats:
        data:
            the_answer: 42
        aggregate: no
        
    - debug: msg={{ packages_installed }}
