- hosts: all
  gather_facts: yes
  vars: 
    my_versions:
      - name: version_1
        version: 1
        released: yes
        license: abc
      - name: version_2
        version: 2
        released: no
        license: abcd

  tasks:      
    - set_fact: current={{ my_versions[number|int] }}
    
    - set_stats: 
        data:
          foo: bar
    
    - command: pwd
      register: pwd_result
      
    - name: check the version specified
      debug: msg={{ current }}
    
    - name: check released version
      debug: msg={{ item.version }}
      with_items: "{{ my_versions }}"
      when: "{{ item.released }}"
      
    # Aggregating packages_installed stat per host
    - set_stats:
      data:
        packages_installed: 31

    # Aggregating random stats for all hosts using complex arguments
    - set_stats:
      data:
        one_stat: 11
        other_stat: "{{ number * 2 }}"
        another_stat: "{{ pwd_result.results | map(attribute='ansible_facts.some_fact') | list }}"
      per_host: no

    # setting stats (not aggregating)
    - set_stats:
      data:
        the_answer: 42
      aggregate: no
