- hosts: all
  gather_facts: yes
  vars: 
    my_versions:
      - name: version_1
        version: 1
        released: yes
        license: abc
      - name: version_2
        version: 2
        released: no
        license: abcd

  tasks:      
    - set_fact: current={{ my_versions[number|int] }}
    
    - set_stats: 
        data:
          foo: bar
       
    - name: check the version specified
      debug: msg={{ current }}
    
    # Aggregating packages_installed stat per host
    - set_stats:
        data:
            packages_installed: 31
      register: stat1
      
    - set_stats:
        data:
            location: mahwah
        aggregate: true    
        per_host: yes
      register: stat2

    # setting stats (not aggregating)
    - set_stats:
        data:
            the_answer: 42
        aggregate: no
      register: stat3
        
    - debug: var=stat1
    - debug: var=stat2
    - debug: var=stat3
