- hosts: all
  gather_facts: false
  vars:
    config_file: "{{ lookup('env', 'OS_CLIENT_CONFIG_FILE') }}"

  tasks:
  - name: display file contents
    debug: var="OS_CLIENT_CONFIG_FILE {{ config_file }}"
    debug: content="Content {{ lookup('file', config_file) }}"
