- hosts: all
  gather_facts: false
  vars:
    config_file: "{{ lookup('env', 'OS_CLIENT_CONFIG_FILE') }}"

  tasks:
  - name: display file contents
    copy:
      src: "{{ config_file }}"
      dest: /tmp/wei.txt 
  - debug: msg="{{ config_file }}"
  - name: sleep a few seconds
    command: "sleep {{ seconds }}"
